name: Security Pipeline

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - ".github/workflows/security-pipeline.yml"

jobs:
  smoke-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Mostrar contexto básico
        run: |
          echo "Workflow ok"
          echo "Branch: $GITHUB_REF"
          echo "Commit: $GITHUB_SHA"
          pwd
          ls -la
